### ISSUE TITLE
Twincat V3.1 4026.10.0 remove  convert old TC2 project capability

### ISSUE THREAD

**Issue by flabb17** [Roald87/TwinCatChangelog#105]
With TwinCAT Standard - Engineering V3.1 4026.10.0, the  option to open and convert  an old TwinCAT 2 project is no more visible in both shell : 
- TCXaeShell64 (64-bit base on visual studio 2022) ![2024-10-03 07_57_55-Window](https://github.com/user-attachments/assets/5723719e-f828-47ac-81b7-91b16ebe04b0)  
- TCXaeShell ( 32-bit historical version base on visual studio 20217) ![image](https://github.com/user-attachments/assets/d0dbf7f7-c074-4742-8c51-b36f780ac85e)

## previous (TC3.1.4024.xxx) 
![2024-10-03 08_01_21-Window](https://github.com/user-attachments/assets/ce880f57-93e5-4c20-9974-ec98e179aaba)

**Comment by Roald87** [comment]
Thanks for reporting!
