### ISSUE TITLE
Request to add the Slack application to this repository

### ISSUE THREAD

**Issue by slacAWallace** [Roald87/TwinCatChangelog#15]
So we can subscribe to it with our Slack channels to get updates!

**Comment by Roald87** [comment]
Sure. What do I need to do for that? Do you have a manual?

**Comment by slacAWallace** [comment]
Honestly not sure, but it looks like it needs this application. I don't know what happens when you install it, if it means my Slack can then connect?

https://github.com/marketplace/slack-github

**Comment by Roald87** [comment]
I installed something. Can you check if it works? I did had to give my payment info, but it is free for now. Not sure if this would change in the future.
