### ISSUE TITLE
TwinCAT 3 library versions

### ISSUE THREAD

**Issue by runtimevic** [Roald87/TwinCatChangelog#16]
Hello @Roald87 ,
look I found this in case you are interested:
https://github.com/RumstiBumsti/TcLibraryVersions

**Comment by Roald87** [comment]
Nice find @runtimevic ! I've contacted the maintainer. There are a few differences between our versions. Once that is cleared up, I think I will link to his repo for the library versions from here.

Thanks!

**Comment by runtimevic** [comment]
> Buen hallazgo @runtimevic! Me he puesto en contacto con el mantenedor. Hay algunas diferencias entre nuestras versiones. Una vez que eso se aclare, creo que enlazaré a su repositorio para las versiones de la biblioteca desde aquí.
> 
> ¡Gracias!

Hi @Roald87 , very nice...

**Comment by Roald87** [comment]
Closed with https://github.com/Roald87/TwinCatChangelog/commit/a5c57be8495507ac97ea9d85c9176fb4da2f35c5
