### ISSUE TITLE
Bosch TwinCAT XAE Changelog

### ISSUE THREAD

**Issue by glonmpo** [Roald87/TwinCatChangelog#26]
Hello,

I hope this hasn't already been posted.
But I found a changelog of TwinCat on the Bosch website. Maybe this helps.

https://community.developer.bosch.com/t5/Knowledge-base/TwinCAT-XAE-version-overview/ta-p/48982#DE

Regards
GlonMPO

**Comment by Roald87** [comment]
Hi GlonMPO,

Thanks for the suggestion! I’ve seen it and incorporated some of the things
listed there in
https://github.com/Roald87/TwinCatChangelog/commit/1135e07b40aa8b5055efaa9d584a843379a1ecf1and
a few corrections here
https://github.com/Roald87/TwinCatChangelog/commit/3d444b5ad85fd82f90d47e95d43ac6c079293b33
and here
https://github.com/Roald87/TwinCatChangelog/commit/059261360a374a093e9e08848511dd0addf4f8bd

But I see it has been updated afterwards. I can have a look which have been
added, but you can also do it with a pull request if you’d like.

Roald.

Op di 5 apr. 2022 om 07:01 schreef glonmpo ***@***.***>
