### ISSUE TITLE
TF5400 V3.1.10.14 released:

### ISSUE THREAD

**Issue by runtimevic** [Roald87/TwinCatChangelog#4]
TF5400 V3.1.10.14 released:
Package includes:
.TF511x TC3 Kinematics Transformation
.TF5410 TC3 Collision Avoidance
.TF5420 TC3 Motion Pick and Place
.TF5430 TC3 Planar Motion
.XPlanar Configurator

TF5420 V3.1.10.14 released:
. New MC Group for Coordinated Motion
. Consistent further development of PnP Group and for
compatibility reasons launched in a new MC Group
. Choice between Geo Blending and Super
Positioning Blending within the new Coordinated
Motion Group
. Uses same PLC library (Tc3_McCoordinatedMotion)

**Comment by Roald87** [comment]
Thanks for your contribution @runtimevic! I added the pages. Is there also a source?

**Comment by runtimevic** [comment]
> Thanks for your contribution @runtimevic! I added the pages. Is there also a source?

[___Beckhoff_automation-update-2021-twincat-e.pdf](https://github.com/Roald87/TwinCatChangelog/files/6746267/___Beckhoff_automation-update-2021-twincat-e.pdf)

**Comment by runtimevic** [comment]
TF511x TC3 Kinematic Transformations
Since V3.1.10.1:
• New function blocks for Extended Rotation Range are implemented.
◦ FB_KinPresetRotation
◦ FB_KinExtendedRotationRange
• New function F_KinAxesInTolerance
• Requires TwinCAT V3.1.4024.7 or newer
Since V3.1.6.3:
• The TF511x TC3 Kinematic Transformations become a part of the TF5400 installation package.

**Comment by Roald87** [comment]
Thanks @runtimevic! You know that you can also propose changes a pull request?

**Comment by runtimevic** [comment]
> You know that you can also propose changes a pull request?

@Roald87, Yes, thanks..
